# -*- coding: utf-8 -*-
"""Analisador Financeiro V2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KSwhMO_2MysN-c6GuPZgl3tWv3ysM63s
"""

# -*- coding: utf-8 -*-
"""Analisador Financeiro V10 - Limite Realista + Alavancagem + PDF"""

import streamlit as st
from matplotlib.backends.backend_pdf import PdfPages
import matplotlib.pyplot as plt
import io
import datetime

# ==============================
# 0️⃣ Login
# ==============================
st.title("🔒 Analisador Financeiro de Clientes")
senha = st.text_input("Digite a senha para acessar o app", type="password")
if senha != "minhaSenhaSegura":
    st.warning("Senha incorreta! Acesso negado.")
    st.stop()

# ==============================
# 1️⃣ Função de análise financeira
# ==============================
def analise_financeira(contas_receber, receita, ativo_circ, estoque, ativo_total,
                       passivo_circ, passivo_total, dividas, patrimonio, lucro, ebitda,
                       caixa, prazo_faturamento, perfil="NORMAL"):

    indicadores = {}

    # --- Liquidez ---
    indicadores['Liquidez Corrente'] = round((ativo_circ / passivo_circ) if passivo_circ else 0, 2)
    indicadores['Liquidez Seca'] = round(((ativo_circ - estoque) / passivo_circ) if passivo_circ else 0, 2)

    # --- Estrutura de Capital ---
    indicadores['Endividamento Total (%)'] = round((passivo_total / ativo_total) * 100 if ativo_total else 0, 2)
    indicadores['Composição do Endividamento (%)'] = round((passivo_circ / passivo_total) * 100 if passivo_total else 0, 2)
    indicadores['Alavancagem (Dívida / PL)'] = round((dividas / patrimonio) if patrimonio else 0, 2)

    # --- Rentabilidade ---
    indicadores['Margem Líquida (%)'] = round((lucro / receita) * 100 if receita else 0, 2)
    indicadores['EBITDA / Receita (%)'] = round((ebitda / receita) * 100 if receita else 0, 2)
    indicadores['ROE (%)'] = round((lucro / patrimonio) * 100 if patrimonio else 0, 2)

    # --- Score para Rating ---
    score = 0
    if indicadores['Endividamento Total (%)'] < 50: score += 2
    if indicadores['Liquidez Corrente'] > 1.2: score += 2
    if indicadores['Liquidez Seca'] > 1: score += 1
    if indicadores['Margem Líquida (%)'] > 10: score += 2
    if indicadores['EBITDA / Receita (%)'] > 15: score += 1
    if indicadores['ROE (%)'] > 10: score += 1

    # Rating
    if score >= 9:
        rating = "A"
    elif score >= 7:
        rating = "B"
    elif score >= 5:
        rating = "C"
    elif score >= 3:
        rating = "D"
    else:
        rating = "E"
    indicadores['Rating do Cliente'] = rating

    # --- Limite de crédito realista ---
    fatura_mensal = (contas_receber / prazo_faturamento) * 30  

    # Fatores
    fator_prazo = 1 + min(prazo_faturamento / 60, 0.2)
    fator_rating = {"A":1.2, "B":1.0, "C":0.8, "D":0.5, "E":0.3}.get(rating,1)
    fator_margem = 1 + (min(indicadores['Margem Líquida (%)'], 15)/100)
    fator_caixa = 0.3 + min(caixa / (dividas + 1e-6), 0.5)

    # Fator passivo circulante
    comp_passivo_circ = indicadores['Composição do Endividamento (%)'] / 100
    if comp_passivo_circ > 0.6:
        fator_passivo = 0.5
    elif comp_passivo_circ > 0.4:
        fator_passivo = 0.7
    else:
        fator_passivo = 1

    # Fator alavancagem
    alav = indicadores['Alavancagem (Dívida / PL)']
    if alav < 2:
        fator_alav = 1
    elif alav <= 5:
        fator_alav = 0.8
    else:
        fator_alav = 0.5

    # Limite final
    limite_credito_ajustado = fatura_mensal * fator_prazo * fator_rating * fator_margem * fator_caixa * fator_passivo * fator_alav

    # Perfil pessimista
    if perfil.upper() == "PESSIMISTA":
        limite_credito_ajustado *= 0.7

    # Limite mínimo se Rating E
    if rating == "E":
        limite_credito_ajustado = 1

    indicadores['Limite de Crédito Sugerido (R$)'] = round(limite_credito_ajustado, 2)
    return indicadores

def recomendacoes(rating):
    rec = {
        "A": "Cliente saudável para crédito. Monitorar apenas fluxos futuros.",
        "B": "Cliente com bom histórico. Revisar condições de pagamento periódicas.",
        "C": "Risco moderado. Avaliar garantias e limites de crédito.",
        "D": "Risco elevado. Exigir garantias adicionais e reduzir limites.",
        "E": "Alto risco. Evitar concessão de crédito sem garantias sólidas."
    }
    return rec.get(rating, "Sem recomendação")

# ==============================
# 2️⃣ Layout Interativo
# ==============================
st.subheader("📌 Informações do Cliente")
col1, col2 = st.columns(2)

with col1:
    nome_cliente = st.text_input("Nome do Cliente")
    data_analise = st.date_input("Data da Análise", datetime.date.today())
    contas_receber = st.number_input("Contas a Receber (R$)", min_value=0.0)
    ativo_circ = st.number_input("Ativo Circulante (R$)", min_value=0.0)
    estoque = st.number_input("Estoques (R$)", min_value=0.0)
    ativo_total = st.number_input("Ativo Total (R$)", min_value=0.0)
    receita = st.number_input("Receita Líquida (R$)", min_value=0.0)
    ebitda = st.number_input("EBITDA (R$)", min_value=0.0)
    caixa = st.number_input("Caixa Disponível (R$)", min_value=0.0)

with col2:
    passivo_circ = st.number_input("Passivo Circulante (R$)", min_value=0.0)
    passivo_total = st.number_input("Passivo Total (R$)", min_value=0.0)
    dividas = st.number_input("Dívidas Totais (R$)", min_value=0.0)
    patrimonio = st.number_input("Patrimônio Líquido (R$)", min_value=0.0)
    lucro = st.number_input("Lucro Líquido (R$)")
    prazo_faturamento = st.number_input("Prazo médio de faturamento (dias)", min_value=1)

perfil = st.selectbox("PERFIL DE CRÉDITO", ["NORMAL", "PESSIMISTA"])

# ==============================
# 3️⃣ Botão de cálculo
# ==============================
if st.button("💡 Calcular Análise Financeira"):
    resultado = analise_financeira(contas_receber, receita, ativo_circ, estoque, ativo_total,
                                   passivo_circ, passivo_total, dividas, patrimonio, lucro, ebitda,
                                   caixa, prazo_faturamento, perfil=perfil)

    # KPIs com emojis
    st.subheader("📊 KPIs Financeiros")
    kpis = {
        "Liquidez Corrente": ("🟢" if resultado['Liquidez Corrente']>1.2 else "🟠", resultado['Liquidez Corrente']),
        "Liquidez Seca": ("🟢" if resultado['Liquidez Seca']>1 else "🟠", resultado['Liquidez Seca']),
        "Endividamento Total (%)": ("🟢" if resultado['Endividamento Total (%)']<50 else "🔴", resultado['Endividamento Total (%)']),
        "Composição do Endividamento (%)": ("🟢" if resultado['Composição do Endividamento (%)']<50 else "🟠", resultado['Composição do Endividamento (%)']),
        "Alavancagem (Dívida / PL)": ("🟠" if resultado['Alavancagem (Dívida / PL)']>5 else "🟢", resultado['Alavancagem (Dívida / PL)']),
        "Margem Líquida (%)": ("🟢" if resultado['Margem Líquida (%)']>10 else "🟠", resultado['Margem Líquida (%)']),
        "EBITDA / Receita (%)": ("🟢" if resultado['EBITDA / Receita (%)']>15 else "🟠", resultado['EBITDA / Receita (%)']),
        "ROE (%)": ("🟢" if resultado['ROE (%)']>10 else "🟠", resultado['ROE (%)']),
        "Limite de Crédito Sugerido (R$)": ("🟢", resultado['Limite de Crédito Sugerido (R$)'])
    }

    for k, (emoji, valor) in kpis.items():
        if "R$" in k:
            st.metric(label=f"{emoji} {k}", value=f"R$ {valor:,.2f}")
        else:
            st.metric(label=f"{emoji} {k}", value=f"{valor:.2f}")

    # Rating e recomendação
    rating = resultado['Rating do Cliente']
    st.subheader("⭐ Rating do Cliente")
    st.markdown(f"**{rating}**", unsafe_allow_html=True)
    st.subheader("📝 Recomendações")
    st.info(recomendacoes(rating))

    # ==============================
    # 4️⃣ PDF gerencial
    # ==============================
    st.subheader("📄 Exportar Relatório em PDF")
    pdf_buffer = io.BytesIO()
    with PdfPages(pdf_buffer) as pdf:
        plt.figure(figsize=(8,10))
        plt.axis('off')
        texto = f"Relatório Financeiro do Cliente\n\nCliente: {nome_cliente}\nData da Análise: {data_analise}\n\n"
        texto += f"=== Inputs fornecidos ===\n"
        texto += f"Contas a Receber: R$ {contas_receber:,.2f}\n"
        texto += f"Ativo Circulante: R$ {ativo_circ:,.2f}\n"
        texto += f"Estoques: R$ {estoque:,.2f}\n"
        texto += f"Ativo Total: R$ {ativo_total:,.2f}\n"
        texto += f"Receita Líquida: R$ {receita:,.2f}\n"
        texto += f"EBITDA: R$ {ebitda:,.2f}\n"
        texto += f"Caixa Disponível: R$ {caixa:,.2f}\n"
        texto += f"Passivo Circulante: R$ {passivo_circ:,.2f}\n"
        texto += f"Passivo Total: R$ {passivo_total:,.2f}\n"
        texto += f"Dívidas Totais: R$ {dividas:,.2f}\n"
        texto += f"Patrimônio Líquido: R$ {patrimonio:,.2f}\n"
        texto += f"Lucro Líquido: R$ {lucro:,.2f}\n"
        texto += f"Prazo médio de faturamento: {prazo_faturamento} dias\n"
        texto += f"Perfil de Crédito: {perfil}\n\n"
        texto += f"=== Indicadores Calculados ===\n"
        for k, v in resultado.items():
            texto += f"{k}: {v}\n"
        plt.text(0, 1, texto, ha='left', va='top', fontsize=10, wrap=True)
        pdf.savefig()
        plt.close()
    pdf_buffer.seek(0)

    st.download_button(
        label="📥 Baixar PDF",
        data=pdf_buffer,
        file_name=f"Relatorio_{nome_cliente}.pdf",
        mime="application/pdf"
    )
