# -*- coding: utf-8 -*-
"""Analisador Financeiro V2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KSwhMO_2MysN-c6GuPZgl3tWv3ysM63s
"""

# -*- coding: utf-8 -*-
"""Analisador Financeiro Profissional"""

import streamlit as st
import datetime
import io
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, Image, PageBreak

# ==============================
# 0️⃣ Configurações iniciais
# ==============================
st.set_page_config(page_title="Analisador Financeiro", layout="wide")
st.title("🔒 Analisador Financeiro de Clientes")

# ==============================
# 0.1 Autenticação
# ==============================
if 'autenticado' not in st.session_state:
    st.session_state['autenticado'] = False

if not st.session_state['autenticado']:
    nome_analista = st.text_input("Nome do Analista")
    senha = st.text_input("Digite a senha para acessar o app", type="password")
    
    if st.button("🔑 Entrar"):
        if not nome_analista:
            st.warning("Informe o nome do analista.")
        elif senha != "minhaSenhaSegura":
            st.error("Senha incorreta! Acesso negado.")
        else:
            st.session_state['autenticado'] = True
            st.session_state['nome_analista'] = nome_analista
            st.success(f"Bem-vindo(a), {nome_analista}!")
    st.stop()

nome_analista = st.session_state['nome_analista']

# ==============================
# 1️⃣ Inputs do cliente
# ==============================
st.subheader("📌 Informações do Cliente")
col1, col2 = st.columns(2)

with col1:
    nome_cliente = st.text_input("Nome do Cliente")
    data_analise = st.date_input("Data da Análise", datetime.date.today())
    contas_receber = st.number_input("Contas a Receber (R$)", min_value=0.0)
    ativo_circ = st.number_input("Ativo Circulante (R$)", min_value=0.0)
    estoque = st.number_input("Estoques (R$)", min_value=0.0)
    ativo_total = st.number_input("Ativo Total (R$)", min_value=0.0)
    receita = st.number_input("Receita Líquida (R$)", min_value=0.0)
    ebitda = st.number_input("EBITDA (R$)", min_value=0.0)
    caixa = st.number_input("Caixa Disponível (R$)", min_value=0.0)
    risco_credito_externo = st.selectbox("Risco de Crédito Externo",
                                         ["Muito Baixo Risco", "Baixo Risco", "Médio Risco", "Alto Risco", "Muito Alto Risco"])

with col2:
    passivo_circ = st.number_input("Passivo Circulante (R$)", min_value=0.0)
    passivo_total = st.number_input("Passivo Total (R$)", min_value=0.0)
    dividas = st.number_input("Dívidas Totais (R$)", min_value=0.0)
    patrimonio = st.number_input("Patrimônio Líquido (R$)", min_value=0.0)
    lucro = st.number_input("Lucro Líquido (R$)", min_value=0.0)
    prazo_faturamento = st.number_input("Prazo médio de faturamento (dias)", min_value=1)
    perfil = st.selectbox("Perfil de Crédito", ["NORMAL", "PESSIMISTA"])

# ==============================
# 2️⃣ Função de análise financeira
# ==============================
def analise_financeira(contas_receber, receita, ativo_circ, estoque, ativo_total,
                       passivo_circ, passivo_total, dividas, patrimonio, lucro, ebitda,
                       caixa, prazo_faturamento, perfil="NORMAL", risco_credito_externo="Médio Risco"):

    indicadores = {}
    indicadores['Liquidez Corrente'] = round((ativo_circ / passivo_circ) if passivo_circ else 0, 2)
    indicadores['Liquidez Seca'] = round(((ativo_circ - estoque) / passivo_circ) if passivo_circ else 0, 2)
    indicadores['Endividamento Total (%)'] = round((passivo_total / ativo_total) * 100 if ativo_total else 0, 2)
    indicadores['Composição do Endividamento (%)'] = round((passivo_circ / passivo_total) * 100 if passivo_total else 0, 2)
    indicadores['Alavancagem (Dívida / PL)'] = round((dividas / patrimonio) if patrimonio else 0, 2)
    indicadores['Margem Líquida (%)'] = round((lucro / receita) * 100 if receita else 0, 2)
    indicadores['EBITDA / Receita (%)'] = round((ebitda / receita) * 100 if receita else 0, 2)
    indicadores['ROE (%)'] = round((lucro / patrimonio) * 100 if patrimonio else 0, 2)

    # Score e rating interno
    score = 0
    if indicadores['Endividamento Total (%)'] < 50: score += 2
    if indicadores['Liquidez Corrente'] > 1.2: score += 2
    if indicadores['Liquidez Seca'] > 1: score += 1
    if indicadores['Margem Líquida (%)'] > 10: score += 2
    if indicadores['EBITDA / Receita (%)'] > 15: score += 1
    if indicadores['ROE (%)'] > 10: score += 1

    if score >= 9: rating = "A"
    elif score >= 7: rating = "B"
    elif score >= 5: rating = "C"
    elif score >= 3: rating = "D"
    else: rating = "E"

    ordem_rating = ["A", "B", "C", "D", "E"]
    impacto = {"Muito Baixo Risco": -1, "Baixo Risco": -1, "Médio Risco":0,
               "Alto Risco":1, "Muito Alto Risco":1}
    idx = ordem_rating.index(rating)
    novo_idx = min(max(idx + impacto.get(risco_credito_externo, 0), 0), 4)
    rating_final = ordem_rating[novo_idx]
    indicadores['Rating do Cliente'] = rating_final

    # Limite de crédito
    fatura_mensal = (contas_receber / prazo_faturamento) * 30
    fator_prazo = 1 + min(prazo_faturamento/120, 0.1)
    rating_map = {"A":1.0,"B":0.9,"C":0.7,"D":0.5,"E":0.3}
    fator_rating = rating_map.get(rating_final, 1)
    fator_margem = min(1, 1 + min(indicadores['Margem Líquida (%)'],15)/100)
    fator_caixa = min(1, 0.3 + min(caixa/(dividas+1e-6),0.5))
    comp_passivo_circ = indicadores['Composição do Endividamento (%)']/100
    if comp_passivo_circ>0.6: fator_passivo = 0.5
    elif comp_passivo_circ>0.4: fator_passivo = 0.7
    else: fator_passivo = 1
    if indicadores['Alavancagem (Dívida / PL)']>5: fator_alavancagem = 0.5
    elif indicadores['Alavancagem (Dívida / PL)']>3: fator_alavancagem = 0.7
    else: fator_alavancagem =1
    limite_credito = fatura_mensal * fator_prazo * fator_rating * fator_margem * fator_caixa * fator_passivo * fator_alavancagem
    if perfil.upper()=="PESSIMISTA": limite_credito *=0.7
    if rating_final=="E": limite_credito = 1
    indicadores['Limite de Crédito Sugerido (R$)'] = round(limite_credito,2)
    return indicadores

# ==============================
# 3️⃣ Recomendações
# ==============================
def recomendacoes(rating):
    rec = {
        "A":"Cliente saudável para crédito. Monitorar apenas fluxos futuros.",
        "B":"Cliente com bom histórico. Revisar condições de pagamento periódicas.",
        "C":"Risco moderado. Avaliar garantias e limites de crédito.",
        "D":"Risco elevado. Exigir garantias adicionais e reduzir limites.",
        "E":"Alto risco. Evitar concessão de crédito sem garantias sólidas."
    }
    return rec.get(rating)

# ==============================
# 4️⃣ Botão de cálculo e exibição KPIs
# ==============================
if st.button("💡 Calcular Análise Financeira"):
    st.session_state['resultado'] = analise_financeira(contas_receber, receita, ativo_circ, estoque, ativo_total,
                                   passivo_circ, passivo_total, dividas, patrimonio, lucro, ebitda,
                                   caixa, prazo_faturamento, perfil, risco_credito_externo)
    st.success("✅ Análise Financeira Calculada com sucesso!")

if 'resultado' in st.session_state:
    resultado = st.session_state['resultado']
    st.subheader("📊 KPIs Financeiros")
    for k,v in resultado.items():
        st.metric(label=k, value=f"R$ {v:,.2f}" if "R$" in k else f"{v}")

    st.subheader("📝 Recomendação")
    st.info(recomendacoes(resultado['Rating do Cliente']))

# ==============================
# 5️⃣ Função para gerar PDF profissional
# ==============================
def gerar_pdf(nome_cliente, data_analise, nome_analista, risco_credito_externo,
              contas_receber, ativo_circ, estoque, ativo_total, receita, ebitda, caixa,
              passivo_circ, passivo_total, dividas, patrimonio, lucro, prazo_faturamento,
              perfil, resultado, recomendacao, logo_path=""):

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4)
    styles = getSampleStyleSheet()
    styleN = styles['Normal']
    styleH = styles['Heading1']

    elementos = []

    # Capa
    if logo_path:
        try:
            elementos.append(Image(logo_path, width=100, height=50))
        except: pass
    elementos.append(Paragraph("<b>Relatório Financeiro Corporativo</b>", styleH))
    elementos.append(Spacer(1,20))
    elementos.append(Paragraph(f"Cliente: {nome_cliente}", styleN))
    elementos.append(Paragraph(f"Analista: {nome_analista}", styleN))
    elementos.append(Paragraph(f"Data da Análise: {data_analise}", styleN))
    elementos.append(Spacer(1,30))
    elementos.append(Paragraph("Este relatório tem caráter corporativo e contém todas as informações financeiras do cliente, incluindo indicadores de liquidez, rentabilidade, endividamento e recomendações de crédito.", styleN))
    elementos.append(PageBreak())

    # Seção Inputs
    elementos.append(Paragraph("📌 Informações Registradas", styles["Heading2"]))
    dados_inputs = [
        ["Contas a Receber", f"R$ {contas_receber:,.2f}"],
        ["Ativo Circulante", f"R$ {ativo_circ:,.2f}"],
        ["Estoques", f"R$ {estoque:,.2f}"],
        ["Ativo Total", f"R$ {ativo_total:,.2f}"],
        ["Receita Líquida", f"R$ {receita:,.2f}"],
        ["EBITDA", f"R$ {ebitda:,.2f}"],
        ["Caixa", f"R$ {caixa:,.2f}"],
        ["Passivo Circulante", f"R$ {passivo_circ:,.2f}"],
        ["Passivo Total", f"R$ {passivo_total:,.2f}"],
        ["Dívidas Totais", f"R$ {dividas:,.2f}"],
        ["Patrimônio Líquido", f"R$ {patrimonio:,.2f}"],
        ["Lucro Líquido", f"R$ {lucro:,.2f}"],
        ["Prazo Médio de Faturamento", f"{prazo_faturamento} dias"],
        ["Perfil de Crédito", perfil],
        ["Risco de Crédito Externo", risco_credito_externo]
    ]
    tabela_inputs = Table(dados_inputs, colWidths=[200,250])
    tabela_inputs.setStyle(TableStyle([("BACKGROUND",(0,0),(0,-1),colors.whitesmoke),
                                       ("GRID",(0,0),(-1,-1),0.5,colors.grey)]))
    elementos.append(tabela_inputs)
    elementos.append(Spacer(1,20))

    # KPIs
    elementos.append(Paragraph("📊 Indicadores Calculados", styles["Heading2"]))
    dados_indicadores = [[k,f"{v}"] for k,v in resultado.items()]
    tabela_indicadores = Table(dados_indicadores, colWidths=[250,200])
    tabela_indicadores.setStyle(TableStyle([("BACKGROUND",(0,0),(0,-1),colors.whitesmoke),
                                            ("GRID",(0,0),(-1,-1),0.5,colors.grey)]))
    elementos.append(tabela_indicadores)
    elementos.append(Spacer(1,20))

    # Recomendações
    elementos.append(Paragraph("📝 Recomendações", styles["Heading2"]))
    elementos.append(Paragraph(recomendacao, styleN))
    elementos.append(Spacer(1,40))

    # Assinatura
    elementos.append(Paragraph("__________________________________", styleN))
    elementos.append(Paragraph(f"Assinatura do Analista - {nome_analista}", styleN))

    doc.build(elementos)
    buffer.seek(0)
    return buffer

